services:
  - type: web
    name: github-mcp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    envVars:
      - key: PORT
        value: 8000
      - key: GITHUB_TOKEN
        value: ""
